import { index, integer, jsonb, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";

export const vehicleConfigurations = pgTable("vehicle_configurations", { id: uuid("id").defaultRandom().primaryKey(), brand: text("brand").notNull(), model: text("model").notNull(), trim: text("trim").notNull(), modelYear: integer("model_year").notNull(), market: text("market").notNull(), catalogSlug: text("catalog_slug").notNull().default(""), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [unique("vehicle_configurations_identity_key").on(t.brand, t.model, t.trim, t.modelYear, t.market), index("vehicle_configurations_catalog_slug_idx").on(t.catalogSlug)]);
export const vehicleConfigurationAliases = pgTable("vehicle_configuration_aliases", { id: uuid("id").defaultRandom().primaryKey(), vehicleConfigurationId: uuid("vehicle_configuration_id").notNull().references(() => vehicleConfigurations.id), aliasNormalized: text("alias_normalized").notNull(), aliasDisplay: text("alias_display").notNull(), kind: text("kind").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [unique("vehicle_configuration_aliases_configuration_alias_key").on(t.vehicleConfigurationId, t.aliasNormalized), index("vehicle_configuration_aliases_normalized_idx").on(t.aliasNormalized)]);
export const schemaContracts = pgTable("schema_contracts", { id: uuid("id").defaultRandom().primaryKey(), label: text("label"), sha256: text("sha256").notNull().unique(), runtimeAssetPath: text("runtime_asset_path").notNull(), recordedAt: timestamp("recorded_at", { withTimezone: true }).defaultNow().notNull() });
export const collectionRuns = pgTable("collection_runs", { id: uuid("id").defaultRandom().primaryKey(), requestId: text("request_id").notNull().unique(), vehicleConfigurationId: uuid("vehicle_configuration_id").notNull().references(() => vehicleConfigurations.id), provider: text("provider").notNull(), modelName: text("model_name").notNull(), status: text("status").notNull(), schemaContractId: uuid("schema_contract_id").notNull().references(() => schemaContracts.id), promptSha256: text("prompt_sha256").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }).notNull(), failureCode: text("failure_code") }, (t) => [index("collection_runs_finished_at_idx").on(t.finishedAt)]);
export const technicalSheetVersions = pgTable("technical_sheet_versions", { id: uuid("id").defaultRandom().primaryKey(), collectionRunId: uuid("collection_run_id").notNull().unique().references(() => collectionRuns.id), vehicleConfigurationId: uuid("vehicle_configuration_id").notNull().references(() => vehicleConfigurations.id), schemaContractId: uuid("schema_contract_id").notNull().references(() => schemaContracts.id), versionNumber: integer("version_number").notNull(), payload: jsonb("payload").notNull(), completenessSummary: jsonb("completeness_summary").notNull(), payloadSha256: text("payload_sha256").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [unique("technical_sheet_versions_vehicle_version_key").on(t.vehicleConfigurationId, t.versionNumber), index("technical_sheet_versions_vehicle_created_idx").on(t.vehicleConfigurationId, t.createdAt)]);
export const sources = pgTable("sources", { id: uuid("id").defaultRandom().primaryKey(), canonicalUrl: text("canonical_url").notNull().unique(), title: text("title").notNull(), sourceType: text("source_type").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const technicalSheetSources = pgTable("technical_sheet_sources", { technicalSheetVersionId: uuid("technical_sheet_version_id").notNull().references(() => technicalSheetVersions.id), sourceId: uuid("source_id").notNull().references(() => sources.id), sourceRef: text("source_ref").notNull() }, (t) => [unique("technical_sheet_sources_version_ref_key").on(t.technicalSheetVersionId, t.sourceRef)]);
