import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from "react";
import { buscarCatalogo, buscarCatalogoTecnico } from "./api";
import { TechnicalFichaWorkspace } from "./TechnicalFichaWorkspace";
import type { CatalogCandidate, CatalogEntryResult, TechnicalCatalogSearchFilters } from "./types";
import { UiButton, UiEmptyState, UiErrorState, UiField, UiLoadingState } from "./ui/primitives";
import "./catalog-workspace.css";

type DiscoveryMode = "identity" | "technical";
type IdentitySearch = { query: string; brand: string; model: string; modelYear: string; market: string };
type AppliedSearch = { mode: "identity"; identity: IdentitySearch; scope: "latest" | "all_versions" } | { mode: "technical"; technical: TechnicalCatalogSearchFilters };
const bodyTypes = ["sedan", "hatch", "suv", "crossover", "cupe", "picape", "caminhonete", "van", "minivan", "utilitario", "conversivel", "wagon", "monovolume", "outro"];
const motorTypes = ["combustao", "eletrico", "hibrido", "hibrido_plugin", "celula_combustivel"];

export interface CatalogWorkspaceProps {
  entry: CatalogEntryResult | null; entryError: string | null; isOpening: boolean; related: CatalogCandidate[]; canCompare: boolean;
  comparisonSelection: Array<CatalogCandidate | null>; onOpen: (candidate: CatalogCandidate) => void; onBack: () => void; onAddToComparison: (candidate: CatalogCandidate) => void; onRemoveFromComparison: (candidate: CatalogCandidate) => void; onGoToComparison: () => void; onExport: (versionId: string, format: "csv" | "json") => void;
}

export function CatalogWorkspace({ canCompare, comparisonSelection, entry, entryError, isOpening, onAddToComparison, onBack, onExport, onGoToComparison, onOpen, onRemoveFromComparison, related }: CatalogWorkspaceProps) {
  const [mode, setMode] = useState<DiscoveryMode>("identity");
  const [identity, setIdentity] = useState<IdentitySearch>({ query: "", brand: "", model: "", modelYear: "", market: "" });
  const [technical, setTechnical] = useState<TechnicalCatalogSearchFilters>({});
  const [scope, setScope] = useState<"latest" | "all_versions">("latest");
  const [results, setResults] = useState<CatalogCandidate[]>([]);
  const [total, setTotal] = useState(0); const [page, setPage] = useState(1);
  const [loadingResults, setLoadingResults] = useState(true); const [resultsError, setResultsError] = useState<string | null>(null); const [isEmpty, setIsEmpty] = useState(false);
  const [appliedSearch, setAppliedSearch] = useState<AppliedSearch>({ mode: "identity", identity: { query: "", brand: "", model: "", modelYear: "", market: "" }, scope: "latest" });
  const [awaitingTechnicalCriteria, setAwaitingTechnicalCriteria] = useState(false);
  const activeIdentityFilters = useMemo(() => appliedSearch.mode === "identity" ? Object.entries(appliedSearch.identity).filter(([, value]) => value.trim()).map(([key, value]) => ({ key, value })) : [], [appliedSearch]);
  const hasAppliedIdentitySearch = appliedSearch.mode === "identity" && (activeIdentityFilters.length > 0 || appliedSearch.scope === "all_versions");
  const hasDraftIdentitySearch = Object.values(identity).some((value) => value.trim()) || scope === "all_versions";

  async function loadIdentity(nextPage = 1, nextScope = scope, nextIdentity = identity) {
    setLoadingResults(true); setResultsError(null);
    setAwaitingTechnicalCriteria(false); setAppliedSearch({ mode: "identity", identity: nextIdentity, scope: nextScope });
    try {
      const hasCriteria = Object.values(nextIdentity).some((value) => value.trim());
      const response = await buscarCatalogo({ query: nextIdentity.query, brand: nextIdentity.brand, model: nextIdentity.model, modelYear: nextIdentity.modelYear, market: nextIdentity.market, page: nextPage, scope: nextScope, sort: hasCriteria ? "alphabetical" : "recent" });
      setResults(response.entries); setTotal(response.total); setPage(nextPage); setIsEmpty(response.state === "not_registered");
    } catch (error) { setResults([]); setTotal(0); setIsEmpty(false); setResultsError(error instanceof Error ? error.message : "Não foi possível consultar o catálogo."); }
    finally { setLoadingResults(false); }
  }
  async function loadTechnical() {
    setLoadingResults(true); setResultsError(null);
    setAwaitingTechnicalCriteria(false); setAppliedSearch({ mode: "technical", technical });
    try { const response = await buscarCatalogoTecnico(technical); setResults(response.entries); setTotal(response.total); setPage(1); setIsEmpty(response.state === "not_registered"); }
    catch (error) { setResults([]); setTotal(0); setIsEmpty(false); setResultsError(error instanceof Error ? error.message : "Não foi possível pesquisar pelas características técnicas."); }
    finally { setLoadingResults(false); }
  }
  useEffect(() => { void loadIdentity(1); }, []);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (mode === "identity") void loadIdentity(1); else void loadTechnical(); }
  function selectMode(nextMode: DiscoveryMode) {
    setMode(nextMode); setResults([]); setTotal(0); setResultsError(null); setIsEmpty(false); setLoadingResults(false);
    if (nextMode === "technical") { setAwaitingTechnicalCriteria(true); return; }
    void loadIdentity(1);
  }
  function clearIdentity() { const cleared = { query: "", brand: "", model: "", modelYear: "", market: "" }; setIdentity(cleared); setScope("latest"); void loadIdentity(1, "latest", cleared); }

  if (entry?.state === "found") {
    const candidate = entry.entry;
    const selected = comparisonSelection.some((item) => item?.latestTechnicalSheetVersionId === candidate.latestTechnicalSheetVersionId);
    const actions: ReactNode = <><UiButton variant="outline" onClick={onBack}>Voltar ao catálogo</UiButton>{canCompare && candidate.latestTechnicalSheetVersionId ? <UiButton onClick={() => selected ? onRemoveFromComparison(candidate) : onAddToComparison(candidate)}>{selected ? "Remover da comparação" : "Adicionar à comparação"}</UiButton> : null}{canCompare && candidate.latestTechnicalSheetVersionId ? <UiButton variant="outline" onClick={() => onExport(candidate.latestTechnicalSheetVersionId!, "csv")}>Exportar CSV</UiButton> : null}{canCompare && candidate.latestTechnicalSheetVersionId ? <UiButton variant="outline" onClick={() => onExport(candidate.latestTechnicalSheetVersionId!, "json")}>Exportar JSON</UiButton> : null}</>;
    return <section className="catalog-workspace catalog-workspace--detail"><TechnicalFichaWorkspace ficha={candidate.response} title={`Ficha catalogada · versão ${candidate.latestVersion ?? "indisponível"}`} contextLabel="Identidade confirmada pelo catálogo." actions={actions} />{canCompare ? <ComparisonTray selection={comparisonSelection} onGo={onGoToComparison} /> : null}{related.length ? <section className="catalog-workspace__related"><h2>Configurações relacionadas por identidade</h2><p>Mesma marca, modelo, ano-modelo e mercado. Isso não confirma compatibilidade para comparar.</p><div>{related.map((item) => <CandidateCard key={item.id} candidate={item} onOpen={onOpen} selection={comparisonSelection} onAddToComparison={onAddToComparison} onRemoveFromComparison={onRemoveFromComparison} />)}</div></section> : <p className="catalog-workspace__related-note">Não há outras fichas relacionadas para esta identidade.</p>}</section>;
  }
  const resultsTitle = awaitingTechnicalCriteria ? "Buscar por características" : appliedSearch.mode === "technical" ? "Correspondências técnicas" : hasAppliedIdentitySearch ? "Resultados da busca" : "Fichas recentes";
  const resultsDescription = awaitingTechnicalCriteria ? "Defina as características técnicas e inicie a busca para consultar correspondências confirmadas." : appliedSearch.mode === "technical" ? "Somente atributos confirmados com fonte rastreável entram nesta busca." : hasAppliedIdentitySearch ? "Confira a identidade antes de abrir qualquer ficha." : "Versões mais recentemente atualizadas no catálogo global autenticado.";
  return <section className="catalog-workspace" aria-labelledby="catalog-title">
    <header className="catalog-workspace__header"><h1 id="catalog-title">Catálogo de fichas</h1><p>Encontre uma configuração persistida e confirme a identidade exata antes de abrir a ficha.</p></header>
    {entry?.state === "incompatible" ? <UiErrorState title="Configuração incompatível" message="Nenhuma ficha foi aberta. Revise a candidata e tente novamente." /> : entry?.state === "not_registered" ? <UiEmptyState title="Ficha não cadastrada" message="Esta configuração ainda não possui uma ficha catalogada." /> : entryError ? <UiErrorState title="Não foi possível abrir a ficha" message={entryError} /> : null}
    <section className="catalog-command" aria-labelledby="catalog-command-title"><div className="catalog-command__intro"><h2 id="catalog-command-title">Encontrar uma configuração</h2><p>{mode === "identity" ? "Pesquise por identidade ou refine apenas quando necessário." : "Compare somente características confirmadas nas fichas persistidas."}</p></div><div className="catalog-command__modes" role="tablist" aria-label="Modo de pesquisa"><button type="button" role="tab" aria-selected={mode === "identity"} onClick={() => selectMode("identity")}>Por identidade</button><button type="button" role="tab" aria-selected={mode === "technical"} onClick={() => selectMode("technical")}>Por características</button></div><form onSubmit={submit}>{mode === "identity" ? <IdentityFilters identity={identity} scope={scope} onChange={setIdentity} onScope={setScope} /> : <TechnicalFilters filters={technical} onChange={setTechnical} />}<div className="catalog-command__actions"><UiButton type="submit" isLoading={loadingResults} loadingLabel="Consultando…">Buscar fichas</UiButton>{mode === "identity" && hasDraftIdentitySearch ? <UiButton variant="outline" disabled={loadingResults} onClick={clearIdentity}>Limpar busca</UiButton> : null}</div></form></section>
    {canCompare ? <ComparisonTray selection={comparisonSelection} onGo={onGoToComparison} /> : null}
    <section className="catalog-results" aria-live="polite" aria-labelledby="catalog-results-title"><div className="catalog-results__heading"><div><h2 id="catalog-results-title">{resultsTitle}</h2><p>{resultsDescription}</p></div>{!loadingResults && !awaitingTechnicalCriteria ? <span>{total} ficha{total === 1 ? "" : "s"}</span> : null}</div>{appliedSearch.mode === "identity" && activeIdentityFilters.length ? <div className="catalog-results__active-filters" aria-label="Filtros aplicados">{activeIdentityFilters.map(({ key, value }) => <span key={key}>{filterLabel(key)}: {value}</span>)}{appliedSearch.scope === "all_versions" ? <span>Versões: todas</span> : null}</div> : null}{awaitingTechnicalCriteria ? <UiEmptyState title="Defina as características para começar" message="A galeria aparece somente depois da busca técnica confirmada." /> : loadingResults ? <UiLoadingState title="Consultando fichas" message="Buscando candidatas no catálogo." /> : resultsError ? <UiErrorState title="Catálogo indisponível" message={resultsError} action={<UiButton variant="outline" onClick={() => appliedSearch.mode === "identity" ? void loadIdentity(page, appliedSearch.scope, appliedSearch.identity) : void loadTechnical()}>Tentar novamente</UiButton>} /> : isEmpty ? <UiEmptyState title={appliedSearch.mode === "technical" ? "Sem correspondência técnica" : "Nenhuma ficha encontrada"} message={appliedSearch.mode === "technical" ? "Os filtros retornam somente características confirmadas. Ajuste os critérios ou procure por identidade." : "Não há ficha catalogada para estes critérios. Limpe a busca ou solicite uma nova coleta."} /> : <><div className="catalog-results__grid">{results.map((candidate) => <CandidateCard key={candidate.id} candidate={candidate} onOpen={onOpen} selection={comparisonSelection} onAddToComparison={onAddToComparison} onRemoveFromComparison={onRemoveFromComparison} />)}</div><Pagination page={page} total={total} disabled={loadingResults || appliedSearch.mode === "technical"} onPrevious={() => appliedSearch.mode === "identity" && void loadIdentity(page - 1, appliedSearch.scope, appliedSearch.identity)} onNext={() => appliedSearch.mode === "identity" && void loadIdentity(page + 1, appliedSearch.scope, appliedSearch.identity)} /></>}</section>
    {isOpening ? <p className="catalog-workspace__opening" role="status">Confirmando a identidade da ficha…</p> : null}
  </section>;
}

function IdentityFilters({ identity, onChange, onScope, scope }: { identity: { query: string; brand: string; model: string; modelYear: string; market: string }; scope: "latest" | "all_versions"; onChange: (next: { query: string; brand: string; model: string; modelYear: string; market: string }) => void; onScope: (scope: "latest" | "all_versions") => void }) {
  const field = (key: keyof typeof identity, label: string) => <UiField label={label}><input value={identity[key]} maxLength={key === "modelYear" ? 4 : 100} inputMode={key === "modelYear" ? "numeric" : undefined} onChange={(event) => onChange({ ...identity, [key]: event.target.value })} /></UiField>;
  return <><div className="catalog-command__primary-field"><UiField label="Marca, modelo ou versão"><input value={identity.query} maxLength={100} placeholder="Ex.: Ford Ranger Raptor" onChange={(event) => onChange({ ...identity, query: event.target.value })} /></UiField></div><details className="catalog-command__filters"><summary>Filtros de identidade e versão</summary><div className="catalog-command__filter-grid">{field("brand", "Marca")}{field("model", "Modelo")}{field("modelYear", "Ano-modelo")}{field("market", "Mercado")}</div><fieldset><legend>Versões exibidas</legend><label><input type="radio" checked={scope === "latest"} onChange={() => onScope("latest")} /> Última por veículo</label><label><input type="radio" checked={scope === "all_versions"} onChange={() => onScope("all_versions")} /> Todas as versões</label></fieldset></details></>;
}
function TechnicalFilters({ filters, onChange }: { filters: TechnicalCatalogSearchFilters; onChange: (filters: TechnicalCatalogSearchFilters) => void }) { return <div className="catalog-command__filter-grid catalog-command__filter-grid--technical"><UiField label="Carroceria"><select value={filters.tipo_carroceria ?? ""} onChange={(event) => onChange({ ...filters, tipo_carroceria: event.target.value || undefined })}><option value="">Qualquer</option>{bodyTypes.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></UiField><UiField label="Propulsão"><select value={filters.motor_tipo ?? ""} onChange={(event) => onChange({ ...filters, motor_tipo: event.target.value || undefined })}><option value="">Qualquer</option>{motorTypes.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></UiField><UiField label="Potência mínima (cv)"><input inputMode="decimal" value={filters.potencia_min_cv ?? ""} onChange={(event) => onChange({ ...filters, potencia_min_cv: event.target.value || undefined })} /></UiField><UiField label="Potência máxima (cv)"><input inputMode="decimal" value={filters.potencia_max_cv ?? ""} onChange={(event) => onChange({ ...filters, potencia_max_cv: event.target.value || undefined })} /></UiField><UiField label="Ano-modelo"><input inputMode="numeric" maxLength={4} value={filters.ano_modelo ?? ""} onChange={(event) => onChange({ ...filters, ano_modelo: event.target.value || undefined })} /></UiField><UiField label="Mercado"><input maxLength={100} value={filters.mercado ?? ""} onChange={(event) => onChange({ ...filters, mercado: event.target.value || undefined })} /></UiField></div>; }
function CandidateCard({ candidate, onAddToComparison, onOpen, onRemoveFromComparison, selection }: { candidate: CatalogCandidate; onAddToComparison: (candidate: CatalogCandidate) => void; onOpen: (candidate: CatalogCandidate) => void; onRemoveFromComparison: (candidate: CatalogCandidate) => void; selection: Array<CatalogCandidate | null> }) { const available = Boolean(candidate.latestTechnicalSheetVersionId); const selected = selection.some((item) => item?.latestTechnicalSheetVersionId === candidate.latestTechnicalSheetVersionId); const full = selection.every(Boolean) && !selected; return <article className={`catalog-candidate${selected ? " is-selected-for-comparison" : ""}`}><div className="catalog-candidate__identity"><h3>{candidate.vehicle.marca} {candidate.vehicle.modelo}</h3><p>{candidate.vehicle.versao}</p></div><dl><div><dt>Ano-modelo</dt><dd>{candidate.vehicle.ano_modelo}</dd></div><div><dt>Mercado</dt><dd>{candidate.vehicle.mercado}</dd></div></dl><div className="catalog-candidate__meta"><span>Versão técnica {candidate.latestVersion ?? "indisponível"}</span>{candidate.latestAt ? <span>Atualizada em {new Date(candidate.latestAt).toLocaleDateString("pt-BR")}</span> : null}</div>{available ? <div className="catalog-candidate__actions"><UiButton variant="outline" onClick={() => onOpen(candidate)}>Abrir ficha exata</UiButton><UiButton variant="ghost" disabled={full} onClick={() => selected ? onRemoveFromComparison(candidate) : onAddToComparison(candidate)}>{selected ? "Remover da comparação" : full ? "Seleção completa" : "Adicionar à comparação"}</UiButton></div> : <p className="catalog-candidate__unavailable">Esta candidata ainda não possui versão técnica para abertura.</p>}</article>; }
function ComparisonTray({ onGo, selection }: { onGo: () => void; selection: Array<CatalogCandidate | null> }) { const count = selection.filter(Boolean).length; return <section className="catalog-comparison-tray" aria-label="Seleção para comparação"><div><span>Seleção para comparação</span><strong>{count}/2 fichas</strong><p>{selection.map((item, index) => item ? `Ficha ${index === 0 ? "X" : "Y"}: ${item.vehicle.marca} ${item.vehicle.modelo}` : `Ficha ${index === 0 ? "X" : "Y"}: aguardando`).join(" · ")}</p></div><UiButton variant="outline" disabled={count === 0} onClick={onGo}>Ir para comparar</UiButton></section>; }
function Pagination({ disabled, onNext, onPrevious, page, total }: { disabled: boolean; onNext: () => void; onPrevious: () => void; page: number; total: number }) { if (total <= 20) return null; return <nav className="catalog-pagination" aria-label="Paginação do catálogo"><UiButton variant="outline" disabled={disabled || page <= 1} onClick={onPrevious}>Página anterior</UiButton><span>Página {page}</span><UiButton variant="outline" disabled={disabled || page * 20 >= total} onClick={onNext}>Próxima página</UiButton></nav>; }
function filterLabel(key: string): string { return ({ query: "Busca", brand: "Marca", model: "Modelo", modelYear: "Ano-modelo", market: "Mercado" } as Record<string, string>)[key] ?? key; }
