import { useEffect, useState } from "react";
import { criarComparacao, listarComparacoes, obterComparacao } from "./api";
import { FichaDiscovery } from "./FichaDiscovery";
import type { CatalogCandidate, SavedComparison } from "./types";

export function ComparisonPanel({ initialCandidate, onInitialCandidateConsumed }: { initialCandidate?: CatalogCandidate | null; onInitialCandidateConsumed?: () => void }) {
  const [selected, setSelected] = useState<CatalogCandidate[]>([]); const [comparison, setComparison] = useState<SavedComparison | null>(null); const [saved, setSaved] = useState<Array<{ id: string; created_at: string; left_version_id: string; right_version_id: string }>>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function refreshSaved() { try { setSaved((await listarComparacoes()).comparisons); } catch (err) { setError(err instanceof Error ? err.message : "Nao foi possivel carregar comparacoes."); } }
  useEffect(() => { void refreshSaved(); }, []);
  useEffect(() => { if (!initialCandidate?.latestTechnicalSheetVersionId) return; setSelected((current) => current.some((item) => item.id === initialCandidate.id) || current.length >= 2 ? current : [...current, initialCandidate]); onInitialCandidateConsumed?.(); }, [initialCandidate, onInitialCandidateConsumed]);
  function toggle(candidate: CatalogCandidate) { if (!candidate.latestTechnicalSheetVersionId) return; setSelected((current) => current.some((item) => item.id === candidate.id) ? current.filter((item) => item.id !== candidate.id) : current.length < 2 ? [...current, candidate] : current); }
  async function compare() { if (selected.length !== 2 || !selected[0].latestTechnicalSheetVersionId || !selected[1].latestTechnicalSheetVersionId) return; try { setLoading(true); setError(null); setComparison(await criarComparacao([selected[0].latestTechnicalSheetVersionId, selected[1].latestTechnicalSheetVersionId])); await refreshSaved(); } catch (err) { setComparison(null); setError(err instanceof Error ? err.message : "Nao foi possivel comparar as fichas."); } finally { setLoading(false); } }
  return <section className="history-layout"><section><h1>Comparar fichas</h1><p>Selecione exatamente duas versões. Mercado e motorização precisam ser compatíveis; ausência e conflito permanecem explícitos.</p><FichaDiscovery onSelect={toggle} selectedIds={selected.map((item) => item.id)} selectionLabel="Selecionar para comparar" />{error ? <div className="error-box" role="alert">{error}</div> : null}<p className="status-text">{selected.length}/2 ficha(s) selecionada(s).</p><button className="primary-button" type="button" disabled={selected.length !== 2 || loading} onClick={() => void compare()}>Comparar e salvar análise</button><h2>Comparações salvas</h2>{saved.length ? saved.map((item) => <button key={item.id} type="button" className="history-item" onClick={() => void obterComparacao(item.id).then(setComparison).catch((err: unknown) => setError(err instanceof Error ? err.message : "Comparacao indisponivel."))}><strong>Análise {item.id.slice(0, 8)}</strong><span>{new Date(item.created_at).toLocaleString("pt-BR")}</span></button>) : <p className="status-text">Nenhuma análise salva nesta organização.</p>}</section><section className="panel history-detail">{comparison ? <ComparisonResult comparison={comparison} /> : <p className="status-text">Selecione duas fichas para comparar.</p>}</section></section>;
}

function ComparisonResult({ comparison }: { comparison: SavedComparison }) { const { left, right, fields } = comparison.comparison; return <><h2>Comparação salva</h2><p className="status-text">{left.vehicle.marca} {left.vehicle.modelo} {left.vehicle.versao} · versão {left.version_number} × {right.vehicle.marca} {right.vehicle.modelo} {right.vehicle.versao} · versão {right.version_number}</p><div className="history-list">{fields.map((field) => <article key={field.path} className="history-item"><strong>{field.label}</strong><span>Esquerda: {formatCell(field.left)}</span><span>Direita: {formatCell(field.right)}</span><span>Estado: {formatDifference(field.difference)}</span>{field.left?.source_refs.length || field.right?.source_refs.length ? <span>Fontes: {[...(field.left?.source_refs ?? []), ...(field.right?.source_refs ?? [])].join(", ")}</span> : null}</article>)}</div></>; }
function formatCell(cell: { value: unknown; unit: string | null; status: string } | null): string { if (!cell) return "Ausente"; const value = cell.value === null || cell.value === undefined ? "Sem valor" : Array.isArray(cell.value) ? cell.value.join(", ") : String(cell.value); return `${value}${cell.unit ? ` ${cell.unit}` : ""} · ${cell.status}`; }
function formatDifference(value: string): string { const labels: Record<string, string> = { equal: "Igual", different: "Diferente", missing_on_left: "Ausente à esquerda", missing_on_right: "Ausente à direita", conflicting: "Conflitante", not_applicable: "Não aplicável" }; return labels[value] ?? value; }
