import { FormEvent, useEffect, useMemo, useState } from "react";
import { buscarCatalogo } from "./api";
import type { CatalogCandidate } from "./types";

export function FichaDiscovery({ onSelect, selectedIds = [], selectionLabel = "Selecionar ficha" }: { onSelect: (candidate: CatalogCandidate) => void; selectedIds?: string[]; selectionLabel?: string }) {
  const [query, setQuery] = useState("");
  const [filters, setFilters] = useState({ brand: "", model: "", modelYear: "", market: "" });
  const [page, setPage] = useState(1); const [entries, setEntries] = useState<CatalogCandidate[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [empty, setEmpty] = useState(false);
  const hasCriteria = useMemo(() => Boolean(query.trim() || filters.brand.trim() || filters.model.trim() || filters.modelYear.trim() || filters.market.trim()), [query, filters]);
  async function load(nextPage = 1) { try { setLoading(true); setError(null); const result = await buscarCatalogo({ query, ...filters, page: nextPage, sort: hasCriteria ? "alphabetical" : "recent" }); setEntries(result.entries); setTotal(result.total); setEmpty(result.state === "not_registered"); setPage(nextPage); } catch (err) { setEntries([]); setTotal(0); setEmpty(false); setError(err instanceof Error ? err.message : "Não foi possível consultar o catálogo."); } finally { setLoading(false); } }
  useEffect(() => { void load(1); }, []);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void load(1); }
  function clear() { setQuery(""); setFilters({ brand: "", model: "", modelYear: "", market: "" }); setTimeout(() => void buscarCatalogo({ page: 1, sort: "recent" }).then((result) => { setEntries(result.entries); setTotal(result.total); setEmpty(result.state === "not_registered"); setPage(1); }).catch((err: unknown) => setError(err instanceof Error ? err.message : "Não foi possível consultar o catálogo.")), 0); }
  return <section className="panel history-panel"><p>{hasCriteria ? "Refine as candidatas pelos filtros ativos." : "Fichas recentes persistidas no catálogo."}</p><form className="form-grid" onSubmit={submit}><label>Marca, modelo ou versão<input value={query} maxLength={100} onChange={(event) => setQuery(event.target.value)} /></label><label>Marca<input value={filters.brand} maxLength={100} onChange={(event) => setFilters((current) => ({ ...current, brand: event.target.value }))} /></label><label>Modelo<input value={filters.model} maxLength={100} onChange={(event) => setFilters((current) => ({ ...current, model: event.target.value }))} /></label><label>Ano-modelo<input value={filters.modelYear} inputMode="numeric" maxLength={4} onChange={(event) => setFilters((current) => ({ ...current, modelYear: event.target.value }))} /></label><label>Mercado<input value={filters.market} maxLength={100} onChange={(event) => setFilters((current) => ({ ...current, market: event.target.value }))} /></label><button className="primary-button" type="submit" disabled={loading}>{loading ? "Consultando..." : "Aplicar filtros"}</button><button className="collapse-all-button" type="button" disabled={loading} onClick={clear}>Limpar filtros</button></form>{hasCriteria ? <p className="status-text">Filtros ativos: {[query && `texto: ${query}`, filters.brand && `marca: ${filters.brand}`, filters.model && `modelo: ${filters.model}`, filters.modelYear && `ano: ${filters.modelYear}`, filters.market && `mercado: ${filters.market}`].filter(Boolean).join(" · ")}</p> : null}{loading ? <p className="status-text" role="status">Carregando fichas recentes...</p> : null}{error ? <div className="error-box" role="alert">{error}</div> : null}{empty ? <p className="status-text" role="status">Nenhuma ficha cadastrada para estes critérios.</p> : null}{entries.length ? <><p className="status-text">{total} ficha(s) encontrada(s).</p><div className="history-list">{entries.map((entry) => <button key={entry.id} type="button" className="history-item" aria-pressed={selectedIds.includes(entry.id)} onClick={() => onSelect(entry)}><strong>{entry.vehicle.marca} {entry.vehicle.modelo} {entry.vehicle.versao}</strong><span><span className="fonte-chip">Ano {entry.vehicle.ano_modelo}</span><span className="fonte-chip">{entry.vehicle.mercado}</span><span className="fonte-chip">Versão {entry.latestVersion ?? "-"}</span></span><span>{selectionLabel}</span></button>)}</div><div className="details-toolbar"><button type="button" className="collapse-all-button" disabled={loading || page <= 1} onClick={() => void load(page - 1)}>Página anterior</button><button type="button" className="collapse-all-button" disabled={loading || page * 20 >= total} onClick={() => void load(page + 1)}>Próxima página</button></div></> : null}</section>;
}
