import { useEffect, useState } from "react";
import { alterarCicloFicha, definirFichaPrimaria, listarConfiguracoesWorkspace, obterFichaTecnicaPorVersao, obterImpactoSessao, obterWorkspaceVeiculo, listarSessoesPesquisa, removerFichaPrimaria } from "./api";
import { TechnicalFichaWorkspace } from "./TechnicalFichaWorkspace";
import type { FichaTecnicaResponse, ResearchSessionImpact, ResearchSessionSummary, VehicleWorkspaceData, VehicleWorkspaceOption, VehicleWorkspaceSheet } from "./types";
import { UiButton, UiEmptyState, UiErrorState, UiLoadingState, UiStatus } from "./ui/primitives";
import "./vehicle-workspace.css";

type ReadState<T> = { status: "idle" | "loading" | "ready" | "error"; data: T | null; error: string | null };
const metricLabels: Record<string, string> = { completeness: "Completude", evidence: "Evidência", consistency: "Consistência", freshness: "Atualidade", human_validation: "Validação humana" };
const qualityMetricKeys = Object.keys(metricLabels);

export function VehicleWorkspace() {
  const [configurationId, setConfigurationId] = useState("");
  const [configurations, setConfigurations] = useState<ReadState<VehicleWorkspaceOption[]>>({ status: "loading", data: null, error: null });
  const [workspace, setWorkspace] = useState<ReadState<VehicleWorkspaceData>>({ status: "idle", data: null, error: null });
  const [selectedSheet, setSelectedSheet] = useState<VehicleWorkspaceSheet | null>(null);
  const [sessions, setSessions] = useState<ReadState<ResearchSessionSummary[]>>({ status: "idle", data: null, error: null });
  const [selectedSession, setSelectedSession] = useState<string | null>(null);
  const [impact, setImpact] = useState<ReadState<ResearchSessionImpact>>({ status: "idle", data: null, error: null });
  const [ficha, setFicha] = useState<ReadState<FichaTecnicaResponse>>({ status: "idle", data: null, error: null });
  const [governance, setGovernance] = useState<{ loading: boolean; message: string | null; error: string | null }>({ loading: false, message: null, error: null });

  useEffect(() => { void loadConfigurations(); }, []);

  async function loadConfigurations() {
    setConfigurations({ status: "loading", data: null, error: null });
    try { setConfigurations({ status: "ready", data: await listarConfiguracoesWorkspace(), error: null }); }
    catch { setConfigurations({ status: "error", data: null, error: "Não foi possível listar os veículos desta organização." }); }
  }

  async function openWorkspace(id: string) {
    setConfigurationId(id);
    setWorkspace({ status: "loading", data: null, error: null }); setSelectedSheet(null); setSelectedSession(null); setImpact({ status: "idle", data: null, error: null }); setSessions({ status: "idle", data: null, error: null }); setFicha({ status: "idle", data: null, error: null });
    try {
      const data = await obterWorkspaceVeiculo(id); setWorkspace({ status: "ready", data, error: null });
      const initial = data.sheets.find((sheet) => sheet.is_primary) ?? data.sheets[0] ?? null;
      if (initial) await selectSheet(initial);
    } catch { setWorkspace({ status: "error", data: null, error: "Não foi possível abrir este workspace. Confirme o acesso e tente novamente." }); }
  }

  async function selectSheet(sheet: VehicleWorkspaceSheet) {
    setSelectedSheet(sheet); setSelectedSession(null); setImpact({ status: "idle", data: null, error: null }); setSessions({ status: "loading", data: null, error: null }); setFicha({ status: sheet.latest_revision ? "loading" : "idle", data: null, error: null });
    const [sessionResult, fichaResult] = await Promise.allSettled([listarSessoesPesquisa(sheet.id), sheet.latest_revision ? obterFichaTecnicaPorVersao(sheet.latest_revision.id) : Promise.resolve(null)]);
    setSessions(sessionResult.status === "fulfilled" ? { status: "ready", data: sessionResult.value, error: null } : { status: "error", data: null, error: "Não foi possível ler o histórico de pesquisas desta ficha." });
    setFicha(fichaResult.status === "fulfilled" ? { status: fichaResult.value ? "ready" : "idle", data: fichaResult.value, error: null } : { status: "error", data: null, error: "Não foi possível abrir a revisão selecionada." });
  }

  async function selectSession(sessionId: string) {
    setSelectedSession(sessionId); setImpact({ status: "loading", data: null, error: null });
    try { setImpact({ status: "ready", data: await obterImpactoSessao(sessionId), error: null }); } catch { setImpact({ status: "error", data: null, error: "O impacto desta sessão não está disponível para sua conta." }); }
  }

  async function refreshWorkspace(sheetId: string) {
    const data = await obterWorkspaceVeiculo(configurationId.trim());
    setWorkspace({ status: "ready", data, error: null });
    const freshSheet = data.sheets.find((sheet) => sheet.id === sheetId) ?? null;
    if (freshSheet) await selectSheet(freshSheet);
  }

  async function runGovernance(action: () => Promise<void>, successMessage: string) {
    if (!selectedSheet) return;
    setGovernance({ loading: true, message: null, error: null });
    try { await action(); await refreshWorkspace(selectedSheet.id); setGovernance({ loading: false, message: successMessage, error: null }); }
    catch { setGovernance({ loading: false, message: null, error: "A alteração não foi concluída. Confirme sua permissão e tente novamente." }); }
  }

  return <section className="vehicle-workspace" aria-labelledby="vehicle-workspace-title">
    <header className="vehicle-workspace__header"><div><p className="vehicle-workspace__eyebrow">Workspace organizacional</p><h1 id="vehicle-workspace-title">Pesquisa e fichas do veículo</h1><p>Escolha um veículo já trabalhado pela organização para consultar fichas, sessões e impacto. Nenhuma pesquisa é iniciada nesta tela.</p></div></header>
    <section className="vehicle-workspace__configuration-picker" aria-labelledby="vehicle-configuration-picker-title"><div><p className="vehicle-workspace__eyebrow">Veículos da organização</p><h2 id="vehicle-configuration-picker-title">Escolha um veículo</h2><p>As configurações aparecem após a criação de uma ficha em uma jornada autorizada.</p></div>{configurations.status === "loading" ? <UiLoadingState title="Carregando veículos" message="Consultando as fichas disponíveis para sua organização." /> : null}{configurations.status === "error" ? <UiErrorState title="Veículos indisponíveis" message={configurations.error ?? "Não foi possível listar os veículos."} action={<UiButton tone="secondary" onClick={() => void loadConfigurations()}>Tentar novamente</UiButton>} /> : null}{configurations.status === "ready" && !configurations.data?.length ? <UiEmptyState title="Nenhum veículo com ficha" message="Crie uma ficha em Nova ficha para que o veículo apareça neste workspace." /> : null}{configurations.data?.length ? <div className="vehicle-workspace__configuration-list">{configurations.data.map((configuration) => <button className="vehicle-configuration-card" type="button" key={configuration.id} aria-current={configurationId === configuration.id ? "true" : undefined} onClick={() => void openWorkspace(configuration.id)}><span className="vehicle-configuration-card__identity"><strong>{configuration.marca} {configuration.modelo}</strong><span>{configuration.versao} · {configuration.ano_modelo} · {configuration.mercado}</span></span><span className="vehicle-configuration-card__meta">{configuration.technical_sheet_count} {configuration.technical_sheet_count === 1 ? "ficha" : "fichas"}</span><span className="vehicle-configuration-card__action">{configurationId === configuration.id && workspace.status === "loading" ? "Abrindo…" : configurationId === configuration.id && workspace.data ? "Aberto" : "Abrir workspace"}</span></button>)}</div> : null}</section>
    {workspace.status === "error" ? <UiErrorState title="Workspace indisponível" message={workspace.error ?? "Não foi possível abrir o workspace."} /> : null}
    {workspace.status === "loading" ? <UiLoadingState title="Abrindo workspace" message="Carregando fichas disponíveis para esta configuração." /> : null}
    {workspace.data ? <>
      <section className="vehicle-workspace__context" aria-label="Contexto da configuração"><div><strong>{workspace.data.vehicle.marca} {workspace.data.vehicle.modelo}</strong><span>{workspace.data.vehicle.versao} · {workspace.data.vehicle.ano_modelo} · {workspace.data.vehicle.mercado}</span></div><dl><div><dt>Última</dt><dd>Revisão temporal por ficha</dd></div><div><dt>Recomendada</dt><dd>Indisponível: política de seleção não configurada</dd></div><div><dt>Primária</dt><dd>{workspace.data.primary ? "Escolha da organização" : "Nenhuma ficha definida"}</dd></div></dl></section>
      <section className="vehicle-workspace__sheets" aria-label="Fichas da organização"><div><h2>Fichas disponíveis</h2><p>Primary, latest e recommended representam conceitos diferentes e não são inferidos pela interface.</p></div><div className="vehicle-workspace__sheet-list">{workspace.data.sheets.length ? workspace.data.sheets.map((sheet) => <SheetCard key={sheet.id} sheet={sheet} selected={selectedSheet?.id === sheet.id} onSelect={() => void selectSheet(sheet)} />) : <UiEmptyState title="Nenhuma ficha nesta organização" message="Crie uma ficha em uma jornada autorizada antes de iniciar uma pesquisa." />}</div></section>
      {selectedSheet ? <section className="vehicle-workspace__research" aria-label="Sessões de pesquisa"><div><h2>Sessões desta ficha</h2><p>O impacto aparece apenas depois da seleção explícita de uma sessão autorizada.</p></div>{sessions.status === "loading" ? <UiLoadingState title="Carregando sessões" message="Consultando o histórico autorizado desta ficha." /> : sessions.status === "error" ? <UiErrorState title="Histórico indisponível" message={sessions.error ?? "Não foi possível ler as sessões."} /> : sessions.data?.length ? <div className="vehicle-workspace__session-list">{sessions.data.map((session) => <SessionCard key={session.id} session={session} selected={selectedSession === session.id} onSelect={() => void selectSession(session.id)} />)}</div> : <UiEmptyState title="Sem sessões de pesquisa" message="Esta ficha ainda não possui uma sessão registrada." />}</section> : null}
      {selectedSheet ? <GovernancePanel sheet={selectedSheet} actions={workspace.data.available_actions} loading={governance.loading} message={governance.message} error={governance.error} onSetPrimary={() => { if (window.confirm("Definir esta ficha como primária da organização?")) void runGovernance(() => definirFichaPrimaria(selectedSheet.id, "reviewed_selection"), "Ficha primária atualizada."); }} onClearPrimary={() => { if (window.confirm("Remover a escolha de ficha primária desta organização?")) void runGovernance(() => removerFichaPrimaria(selectedSheet.id), "Ficha primária removida."); }} onTransition={(state, reason) => { if (window.confirm(`Alterar o ciclo de vida desta ficha para ${lifecycleLabel(state)}?`)) void runGovernance(() => alterarCicloFicha(selectedSheet.id, state, reason), "Ciclo de vida atualizado."); }} /> : null}
      {selectedSheet ? <TechnicalFichaWorkspace ficha={ficha.data} isLoading={ficha.status === "loading"} error={ficha.error} technicalSheetVersionId={selectedSheet.latest_revision?.id} title={selectedSheet.latest_revision ? `Ficha da organização · revisão ${selectedSheet.latest_revision.number}` : "Ficha da organização"} contextLabel="A ficha permanece legível enquanto o impacto é consultado em uma aba própria." historyContent={<SessionHistory sessions={sessions.data ?? []} />} researchContent={<ResearchImpactPanel impact={impact} selected={Boolean(selectedSession)} onRetry={selectedSession ? () => void selectSession(selectedSession) : undefined} />} /> : null}
    </> : null}
  </section>;
}

function SheetCard({ onSelect, selected, sheet }: { onSelect: () => void; selected: boolean; sheet: VehicleWorkspaceSheet }) { return <article className="vehicle-sheet-card"><div><h3>Ficha {sheet.latest_revision ? `· revisão ${sheet.latest_revision.number}` : "sem revisão"}</h3><p>Estado: {sheet.state === "active" ? "ativa" : sheet.state === "stale" ? "desatualizada" : "arquivada"}.</p><div className="vehicle-sheet-card__tags">{sheet.is_primary ? <UiStatus tone="entry" label="Primária da organização" /> : null}{sheet.tags.map((tag) => <UiStatus key={`${tag.origin}-${tag.tag}`} tone={tag.tag === "has_conflicts" ? "conflict" : tag.tag === "incomplete" || tag.tag === "outdated" || tag.tag === "archived" ? "partial" : "entry"} label={`${tag.tag.replaceAll("_", " ")} · ${tag.origin === "manual" ? "manual" : "derivada"}`} />)}</div></div><UiButton tone={selected ? "primary" : "secondary"} onClick={onSelect}>{selected ? "Ficha selecionada" : "Selecionar ficha"}</UiButton></article>; }
function GovernancePanel({ actions, error, loading, message, onClearPrimary, onSetPrimary, onTransition, sheet }: { actions: VehicleWorkspaceData["available_actions"]; error: string | null; loading: boolean; message: string | null; onSetPrimary: () => void; onClearPrimary: () => void; onTransition: (state: "active" | "stale" | "archived", reason: "freshness_policy" | "manual_review" | "superseded" | "restored_after_review") => void; sheet: VehicleWorkspaceSheet }) {
  const transitions = lifecycleTransitions(sheet.state);
  return <section className="vehicle-governance" aria-labelledby="vehicle-governance-title"><div><p>Governança da ficha selecionada</p><h2 id="vehicle-governance-title">Estado, seleção e tags</h2><p>Primary é uma escolha auditável da organização; latest é temporal; recommended continua indisponível.</p></div><div className="vehicle-governance__actions">{actions.manage_primary ? sheet.is_primary ? <UiButton tone="secondary" disabled={loading} onClick={onClearPrimary}>Remover como primária</UiButton> : <UiButton disabled={loading || sheet.state === "archived"} onClick={onSetPrimary}>Definir como primária</UiButton> : <p>Você não possui capacidade para alterar a ficha primária.</p>}{actions.manage_lifecycle && transitions.length ? <fieldset disabled={loading}><legend>Alterar ciclo de vida</legend>{transitions.map((transition) => <UiButton key={transition.state} tone="secondary" onClick={() => onTransition(transition.state, transition.reason)}>{lifecycleLabel(transition.state)}</UiButton>)}</fieldset> : !actions.manage_lifecycle ? <p>Você não possui capacidade para alterar o ciclo de vida.</p> : null}</div><p className="vehicle-governance__tags-note">Tags manuais e derivadas permanecem identificadas nos cards. A capability específica para mutar tags não está no contrato atual do workspace; por isso nenhuma ação de tag é oferecida aqui.</p>{message ? <p className="vehicle-governance__message" role="status">{message}</p> : null}{error ? <p className="vehicle-governance__error" role="alert">{error}</p> : null}</section>;
}
function SessionCard({ onSelect, selected, session }: { onSelect: () => void; selected: boolean; session: ResearchSessionSummary }) { return <article className="vehicle-session-card"><div><h3>{humanize(session.focus)}</h3><p>{session.finished_at ? `Finalizada em ${formatDate(session.finished_at)}` : `Criada em ${formatDate(session.created_at)}`}</p><p>Estado: {outcomeLabel(session.state)}{session.stop_reason ? ` · ${humanize(session.stop_reason)}` : ""}</p></div><UiButton tone={selected ? "primary" : "secondary"} onClick={onSelect}>{selected ? "Impacto selecionado" : "Ver impacto"}</UiButton></article>; }
function SessionHistory({ sessions }: { sessions: ResearchSessionSummary[] }) { if (!sessions.length) return <UiEmptyState title="Histórico indisponível" message="Selecione uma ficha com sessões autorizadas para consultar este histórico." />; return <ol className="vehicle-session-history">{sessions.map((session) => <li key={session.id}><strong>{humanize(session.focus)}</strong><span>{outcomeLabel(session.state)} · {formatDate(session.finished_at ?? session.created_at)}</span></li>)}</ol>; }
function ResearchImpactPanel({ impact, onRetry, selected }: { impact: ReadState<ResearchSessionImpact>; onRetry?: () => void; selected: boolean }) {
  if (!selected) return <UiEmptyState title="Selecione uma sessão" message="O impacto é específico da sessão. Escolha uma sessão acima para ler os vetores e a recomendação disponíveis." />;
  if (impact.status === "loading") return <UiLoadingState title="Carregando impacto" message="Lendo o resultado já calculado desta sessão, sem iniciar uma nova pesquisa." />;
  if (impact.status === "error") return <UiErrorState title="Impacto indisponível" message={impact.error ?? "Não foi possível ler o impacto."} action={onRetry ? <UiButton tone="secondary" onClick={onRetry}>Tentar novamente</UiButton> : undefined} />;
  if (!impact.data) return <UiEmptyState title="Impacto ainda indisponível" message="Esta sessão não possui um resultado de impacto disponível." />;
  const result = impact.data; const hasAfter = result.after !== null;
  const metrics = qualityMetricKeys.flatMap((key) => result.before[key] ? [[key, result.before[key]] as const] : []);
  return <section className="research-impact" aria-labelledby="research-impact-title"><header><div><p>Impacto da sessão selecionada</p><h2 id="research-impact-title">{outcomeLabel(result.outcome_kind)}</h2></div><UiStatus tone={outcomeTone(result.outcome_kind)} label={outcomeLabel(result.outcome_kind)} /></header><p className="research-impact__outcome">{outcomeDescription(result.outcome_kind)}</p>{hasAfter ? <div className="research-impact__metrics" aria-label="Vetores antes e depois">{metrics.map(([key, before]) => { const after = result.after?.[key]; const delta = isDeltaRecord(result.delta) ? result.delta[key] : undefined; return <article key={key}><h3>{metricLabels[key]}</h3><dl><div><dt>Antes</dt><dd>{formatMetric(before)}</dd></div><div><dt>Depois</dt><dd>{after ? formatMetric(after) : "Indisponível"}</dd></div><div><dt>Delta</dt><dd>{delta ? formatDelta(delta.rate_delta) : "Indisponível"}</dd></div></dl></article>; })}</div> : <UiEmptyState title="Sem revisão publicada" message="O resultado não publicou uma nova revisão; por isso não existe vetor depois nem ganho calculado." />}<section className="research-impact__recommendation" aria-label="Recomendação não mandatória"><h3>Próxima ação sugerida</h3><p>{result.recommendation.reason ?? "Não há uma razão adicional disponível."}</p><dl><div><dt>Foco</dt><dd>{result.recommendation.focus ? humanize(result.recommendation.focus) : "Indisponível"}</dd></div><div><dt>Impacto esperado</dt><dd>{result.recommendation.expected_impact ?? "Indisponível"}</dd></div><div><dt>Política</dt><dd>{result.policy_version}</dd></div></dl><p className="research-impact__alternative">Alternativa explícita: não pesquisar agora.</p></section></section>;
}
function formatMetric(metric: { numerator: number; denominator: number; rate: number }): string { return `${metric.numerator}/${metric.denominator} · ${(metric.rate * 100).toFixed(0)}%`; }
function formatDelta(rate: number): string { const percentage = rate * 100; return `${percentage > 0 ? "+" : ""}${percentage.toFixed(0)} p.p.`; }
function isDeltaRecord(value: ResearchSessionImpact["delta"]): value is Record<string, { numerator_delta: number; denominator_delta: number; rate_delta: number }> { return !("state" in value); }
function outcomeLabel(value: string): string { return ({ published: "Revisão publicada", partial_published: "Revisão parcialmente publicada", research_exhausted: "Pesquisa esgotada", failed: "Pesquisa não concluída", cancelled: "Pesquisa cancelada", needs_rebase: "Revisão-base desatualizada", succeeded: "Pesquisa concluída", partial: "Pesquisa parcial", queued: "Aguardando execução", running: "Em execução" } as Record<string, string>)[value] ?? humanize(value); }
function outcomeDescription(value: string): string { return ({ published: "Uma nova revisão foi publicada e os vetores podem ser comparados.", partial_published: "Uma revisão parcial foi publicada; lacunas e conflitos continuam preservados.", research_exhausted: "A pesquisa atingiu sua condição de parada sem publicar nova revisão.", failed: "A pesquisa não foi concluída; não há ganho de qualidade calculado.", cancelled: "A pesquisa foi cancelada antes da publicação; não há ganho calculado.", needs_rebase: "A revisão-base ficou desatualizada e exige uma decisão de continuidade." } as Record<string, string>)[value] ?? "O estado desta sessão é apresentado como informado pelo servidor."; }
function outcomeTone(value: string): "confirmed" | "partial" | "conflict" | "not-found" | "entry" { return value === "published" ? "confirmed" : value === "partial_published" ? "partial" : value === "needs_rebase" || value === "failed" ? "conflict" : value === "research_exhausted" || value === "cancelled" ? "not-found" : "entry"; }
function lifecycleTransitions(state: VehicleWorkspaceSheet["state"]): Array<{ state: "active" | "stale" | "archived"; reason: "freshness_policy" | "manual_review" | "superseded" | "restored_after_review" }> { if (state === "active") return [{ state: "stale", reason: "manual_review" }, { state: "archived", reason: "superseded" }]; if (state === "stale") return [{ state: "active", reason: "restored_after_review" }, { state: "archived", reason: "superseded" }]; return [{ state: "active", reason: "restored_after_review" }]; }
function lifecycleLabel(state: "active" | "stale" | "archived"): string { return ({ active: "Marcar como ativa", stale: "Marcar como desatualizada", archived: "Arquivar ficha" } as Record<string, string>)[state]; }
function humanize(value: string): string { const text = value.replaceAll("_", " "); return text.charAt(0).toUpperCase() + text.slice(1); }
function formatDate(value: string): string { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "data indisponível" : parsed.toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }); }
