import { and, asc, desc, eq } from "drizzle-orm";
import type { AuthContext } from "./authentication";
import { getDatabase } from "./db/client";
import { collectionRuns, fieldResearchStates, researchSessions, researchSessionTasks, technicalSheets, technicalSheetVersions, vehicleConfigurations } from "./db/schema";
import { HttpError } from "./types";
import { readFieldPolicy, readFieldStatePolicy, readNormalizationPolicy, readQualityPolicy, readResearchPlanPolicy, readSourcePolicy } from "./runtime-assets";
import { readBaseAgentPrompt, buildVehiclePayload, composeFinalPrompt, readOutputSchema } from "./prompt-builder";
import { callLLMSimulated } from "./llm";
import { validateResponse } from "./validator";
import { persistTechnicalSheet } from "./db/repository";
import { buildResearchPlan, researchFocuses, type ResearchFocus, type ResearchPlan, type ResearchPlanTask } from "./research-plan";
import { recordResearchSessionQualityImpact } from "./research-session-quality-impact";
import { projectResearchState } from "./field-state";
import { appendResearchSessionEvent } from "./research-session-history";

export { researchFocuses, type ResearchFocus } from "./research-plan";
export interface CreateResearchSessionInput { sheetId: string; idempotencyKey: string; focus: ResearchFocus; category?: string; variables?: string[]; actor: AuthContext; requestId: string; }

export async function createResearchSession(input: CreateResearchSessionInput): Promise<{ id: string; state: string; request_id: string }> {
  const db = getDatabase(); if (!db) throw new HttpError(503, "Persistencia PostgreSQL indisponivel.");
  const [sourcePolicy, planPolicy, fieldStatePolicy] = await Promise.all([readSourcePolicy(), readResearchPlanPolicy(), readFieldStatePolicy()]);
  const result = await db.transaction(async (tx) => {
    const [sheet] = await tx.select({ id: technicalSheets.id }).from(technicalSheets).where(and(eq(technicalSheets.id, input.sheetId), eq(technicalSheets.organizationId, input.actor.organizationId))).limit(1);
    if (!sheet) throw new HttpError(404, "Ficha indisponivel.");
    const [existing] = await tx.select({ id: researchSessions.id, state: researchSessions.state }).from(researchSessions).where(and(eq(researchSessions.organizationId, input.actor.organizationId), eq(researchSessions.technicalSheetId, sheet.id), eq(researchSessions.idempotencyKey, input.idempotencyKey))).limit(1);
    if (existing) return { id: existing.id, state: existing.state, request_id: input.requestId };
    const [base] = await tx.select({ id: technicalSheetVersions.id, payload: technicalSheetVersions.payload, schemaContractId: technicalSheetVersions.schemaContractId, vehicle: vehicleConfigurations }).from(technicalSheetVersions).innerJoin(collectionRuns, eq(technicalSheetVersions.collectionRunId, collectionRuns.id)).innerJoin(vehicleConfigurations, eq(technicalSheetVersions.vehicleConfigurationId, vehicleConfigurations.id)).where(and(eq(technicalSheetVersions.technicalSheetId, sheet.id), eq(collectionRuns.organizationId, input.actor.organizationId))).orderBy(desc(technicalSheetVersions.createdAt), desc(technicalSheetVersions.id)).limit(1);
    if (!base) throw new HttpError(409, "Ficha sem revisao elegivel.");
    const plan = buildResearchPlan({ payload: base.payload, focus: input.focus, category: input.category, variables: input.variables, brand: base.vehicle.brand, market: base.vehicle.market, sourcePolicy, planPolicy });
    const exhausted = Boolean(plan.exhaustionReason);
    const [created] = await tx.insert(researchSessions).values({ technicalSheetId: sheet.id, baseRevisionId: base.id, organizationId: input.actor.organizationId, accountId: input.actor.accountId, memberId: input.actor.memberId, idempotencyKey: input.idempotencyKey, focus: input.focus, requestedTargets: { category: input.category ?? null, variables: input.variables ?? [] }, resolvedTargets: plan.tasks.flatMap((task) => task.targetPaths), sourcePolicyVersion: sourcePolicy.version, runtimeContractVersion: "research-session-v2-directed", researchPlanVersion: plan.version, researchPlan: plan, schemaContractId: base.schemaContractId, budget: { max_tasks: plan.taskCount, max_provider_calls: plan.providerCallBudget, provider_calls: 0, mode: "prepared" }, state: exhausted ? "research_exhausted" : "queued", stopReason: plan.exhaustionReason ?? null, finishedAt: exhausted ? new Date() : null }).returning({ id: researchSessions.id, state: researchSessions.state });
    if (!created) throw new HttpError(409, "Sessao indisponivel.");
    if (plan.tasks.length) await tx.insert(researchSessionTasks).values(plan.tasks.map((task) => ({ researchSessionId: created.id, sequenceNumber: task.sequence, kind: task.kind, targetPaths: task.targetPaths, sourceStrategy: task.sourceStrategy, officialDomains: task.officialDomains, allowedSourceTypes: task.allowedSourceTypes, providerCallBudget: task.providerCallBudget, state: "queued" })));
    const projectedState = projectResearchState(created.state);
    const paths = plan.tasks.flatMap((task) => task.targetPaths);
    if (projectedState && paths.length) await tx.insert(fieldResearchStates).values(paths.map((path) => ({ researchSessionId: created.id, technicalSheetId: sheet.id, baseRevisionId: base.id, path, stateVersion: fieldStatePolicy.version, state: projectedState, reasonCode: plan.exhaustionReason ?? "research_pending" })));
    await appendResearchSessionEvent(tx, { sessionId: created.id, organizationId: input.actor.organizationId, type: "session_planned", correlationId: input.requestId, metadata: { runtime_contract_version: "research-session-v2-directed", research_plan_version: plan.version, source_policy_version: sourcePolicy.version, provider_call_budget: plan.providerCallBudget, state: created.state, base_revision_id: base.id } });
    if (exhausted) await appendResearchSessionEvent(tx, { sessionId: created.id, organizationId: input.actor.organizationId, type: "session_exhausted", correlationId: input.requestId, metadata: { state: created.state, stop_reason: plan.exhaustionReason ?? "research_exhausted" } });
    return { id: created.id, state: created.state, request_id: input.requestId };
  });
  if (result.state === "research_exhausted") await recordResearchSessionQualityImpact(result.id);
  return result;
}

export async function executeResearchSession(sessionId: string, actor: AuthContext, requestId: string): Promise<{ id: string; state: string; technical_sheet_id: string; vehicle_configuration_id: string }> {
  const db = getDatabase(); if (!db) throw new HttpError(503, "Persistencia PostgreSQL indisponivel.");
  const session = await db.transaction(async (tx) => {
    const [row] = await tx.select({ session: researchSessions, version: technicalSheetVersions, vehicle: vehicleConfigurations }).from(researchSessions).innerJoin(technicalSheetVersions, eq(researchSessions.baseRevisionId, technicalSheetVersions.id)).innerJoin(vehicleConfigurations, eq(technicalSheetVersions.vehicleConfigurationId, vehicleConfigurations.id)).where(and(eq(researchSessions.id, sessionId), eq(researchSessions.organizationId, actor.organizationId))).limit(1);
    if (!row) throw new HttpError(404, "Sessao indisponivel."); if (row.session.state !== "queued") throw new HttpError(409, "Sessao indisponivel.");
    const [task] = await tx.select().from(researchSessionTasks).where(and(eq(researchSessionTasks.researchSessionId, sessionId), eq(researchSessionTasks.state, "queued"))).orderBy(asc(researchSessionTasks.sequenceNumber)).limit(1);
    if (!task) throw new HttpError(409, "Plano indisponivel.");
    const [started] = await tx.update(researchSessions).set({ state: "running", startedAt: new Date() }).where(and(eq(researchSessions.id, sessionId), eq(researchSessions.state, "queued"))).returning();
    if (!started) throw new HttpError(409, "Sessao indisponivel.");
    await tx.update(researchSessionTasks).set({ state: "running", startedAt: new Date() }).where(and(eq(researchSessionTasks.id, task.id), eq(researchSessionTasks.state, "queued")));
    await appendResearchSessionEvent(tx, { sessionId, organizationId: actor.organizationId, type: "execution_started", correlationId: requestId, metadata: { state: "running", task_sequence: task.sequenceNumber, provider_call_budget: task.providerCallBudget } });
    await appendResearchSessionEvent(tx, { sessionId, organizationId: actor.organizationId, type: "task_started", correlationId: requestId, metadata: { state: "running", task_sequence: task.sequenceNumber, provider_call_budget: task.providerCallBudget } });
    return { ...row, task };
  });
  const task = toResearchPlanTask(session.task);
  try {
    const vehicle = { marca: session.vehicle.brand, modelo: session.vehicle.model, versao: session.vehicle.trim, ano_modelo: session.vehicle.modelYear, mercado: session.vehicle.market };
    const [schema, basePrompt, sourcePolicy, normalizationPolicy, fieldPolicy, qualityPolicy, fieldStatePolicy] = await Promise.all([readOutputSchema(), readBaseAgentPrompt(), readSourcePolicy(), readNormalizationPolicy(), readFieldPolicy(), readQualityPolicy(), readFieldStatePolicy()]);
    const raw = await callLLMSimulated(composeFinalPrompt({ baseAgentPrompt: basePrompt, outputSchema: schema, vehiclePayload: buildVehiclePayload(vehicle), sourcePolicy: sourcePolicyForTask(sourcePolicy, task), normalizationPolicy, fieldPolicy, qualityPolicy, fieldStatePolicy, researchPlanTask: task }), vehicle);
    const response = validateResponse(raw, schema, { vehicle, provider: "simulated", sourcePolicy, normalizationPolicy, fieldPolicy, qualityPolicy, fieldStatePolicy });
    if (task.sourceStrategy === "official_only" && !hasOfficialEvidence(response, sourcePolicy, task)) return finishExhausted(db, session.session.id, session.task.id, session.session.technicalSheetId, session.vehicle.id, "official_evidence_not_found", requestId, actor.organizationId);
    await persistTechnicalSheet({ requestId: `research-${session.session.id}`, provider: "simulated", vehicle, response, outputSchema: schema, finalPrompt: "research-session-directed-simulated", actor, auditAction: "technical_sheet.generated", technicalSheetId: session.session.technicalSheetId, expectedBaseRevisionId: session.session.baseRevisionId });
    const state = hasUnresolvedTarget(response, task.targetPaths) ? "partial" : "succeeded";
    await db.transaction(async (tx) => {
      const [publishedRevision] = await tx.select({ id: technicalSheetVersions.id }).from(technicalSheetVersions).innerJoin(collectionRuns, eq(technicalSheetVersions.collectionRunId, collectionRuns.id)).where(and(eq(collectionRuns.requestId, `research-${session.session.id}`), eq(collectionRuns.organizationId, actor.organizationId))).limit(1);
      if (!publishedRevision) throw new HttpError(409, "Revisao publicada indisponivel.");
      await tx.update(researchSessionTasks).set({ state, providerCallsUsed: 1, stopReason: state === "partial" ? "eligible_targets_unresolved" : "plan_completed", finishedAt: new Date() }).where(eq(researchSessionTasks.id, session.task.id));
      await tx.update(researchSessions).set({ state, finishedAt: new Date(), stopReason: state === "partial" ? "eligible_targets_unresolved" : "plan_completed", budget: { max_tasks: 1, max_provider_calls: task.providerCallBudget, provider_calls: 1, mode: "simulated" } }).where(eq(researchSessions.id, session.session.id));
      if (state === "partial") await tx.update(fieldResearchStates).set({ state: "research_exhausted", reasonCode: "eligible_targets_unresolved", updatedAt: new Date() }).where(eq(fieldResearchStates.researchSessionId, session.session.id));
      await appendResearchSessionEvent(tx, { sessionId: session.session.id, organizationId: actor.organizationId, type: "task_finished", correlationId: requestId, metadata: { state, task_sequence: session.task.sequenceNumber, provider_calls_used: 1, stop_reason: state === "partial" ? "eligible_targets_unresolved" : "plan_completed" } });
      await appendResearchSessionEvent(tx, { sessionId: session.session.id, organizationId: actor.organizationId, type: "revision_published", correlationId: requestId, metadata: { state, base_revision_id: session.session.baseRevisionId, result_revision_id: publishedRevision.id } });
    });
    await recordResearchSessionQualityImpact(session.session.id);
    return { id: session.session.id, state, technical_sheet_id: session.session.technicalSheetId, vehicle_configuration_id: session.vehicle.id };
  } catch (error) {
    const state = error instanceof HttpError && error.statusCode === 409 ? "needs_rebase" : "failed";
    await db.transaction(async (tx) => {
      await tx.update(researchSessionTasks).set({ state, providerCallsUsed: 1, stopReason: state === "needs_rebase" ? "base_revision_stale" : "execution_failed", finishedAt: new Date() }).where(eq(researchSessionTasks.id, session.task.id));
      await tx.update(researchSessions).set({ state, failureCode: state, stopReason: state === "needs_rebase" ? "base_revision_stale" : "execution_failed", finishedAt: new Date(), budget: { max_tasks: 1, max_provider_calls: task.providerCallBudget, provider_calls: 1, mode: "simulated" } }).where(eq(researchSessions.id, session.session.id));
      await tx.update(fieldResearchStates).set({ state: "blocked", reasonCode: state === "needs_rebase" ? "base_revision_stale" : "execution_failed", updatedAt: new Date() }).where(eq(fieldResearchStates.researchSessionId, session.session.id));
      await appendResearchSessionEvent(tx, { sessionId: session.session.id, organizationId: actor.organizationId, type: "task_finished", correlationId: requestId, metadata: { state, task_sequence: session.task.sequenceNumber, provider_calls_used: 1, stop_reason: state === "needs_rebase" ? "base_revision_stale" : "execution_failed" } });
      await appendResearchSessionEvent(tx, { sessionId: session.session.id, organizationId: actor.organizationId, type: "session_failed", correlationId: requestId, metadata: { state, failure_code: state, stop_reason: state === "needs_rebase" ? "base_revision_stale" : "execution_failed" } });
    });
    await recordResearchSessionQualityImpact(session.session.id);
    throw error;
  }
}

export async function cancelResearchSession(sessionId: string, actor: AuthContext): Promise<{ id: string; state: "cancelled" }> { const db = getDatabase(); if (!db) throw new HttpError(503, "Persistencia PostgreSQL indisponivel."); const row = await db.transaction(async (tx) => { const [updated] = await tx.update(researchSessions).set({ state: "cancelled", stopReason: "cancelled_by_user", finishedAt: new Date() }).where(and(eq(researchSessions.id, sessionId), eq(researchSessions.organizationId, actor.organizationId), eq(researchSessions.state, "queued"))).returning({ id: researchSessions.id }); if (!updated) throw new HttpError(409, "Sessao indisponivel."); await tx.update(researchSessionTasks).set({ state: "cancelled", stopReason: "cancelled_by_user", finishedAt: new Date() }).where(and(eq(researchSessionTasks.researchSessionId, sessionId), eq(researchSessionTasks.state, "queued"))); await tx.update(fieldResearchStates).set({ state: "blocked", reasonCode: "cancelled_by_user", updatedAt: new Date() }).where(eq(fieldResearchStates.researchSessionId, sessionId)); await appendResearchSessionEvent(tx, { sessionId, organizationId: actor.organizationId, type: "session_cancelled", correlationId: `cancel-${sessionId}`, metadata: { state: "cancelled", stop_reason: "cancelled_by_user" } }); return updated; }); await recordResearchSessionQualityImpact(row.id); return { id: row.id, state: "cancelled" }; }
export async function listResearchSessions(sheetId: string, actor: AuthContext): Promise<unknown[]> { const db = getDatabase(); if (!db) throw new HttpError(503, "Persistencia PostgreSQL indisponivel."); const rows = await db.select({ id: researchSessions.id, focus: researchSessions.focus, state: researchSessions.state, runtimeContractVersion: researchSessions.runtimeContractVersion, researchPlanVersion: researchSessions.researchPlanVersion, researchPlan: researchSessions.researchPlan, budget: researchSessions.budget, stopReason: researchSessions.stopReason, createdAt: researchSessions.createdAt, finishedAt: researchSessions.finishedAt }).from(researchSessions).where(and(eq(researchSessions.technicalSheetId, sheetId), eq(researchSessions.organizationId, actor.organizationId))).orderBy(desc(researchSessions.createdAt)).limit(20); return rows.map(x => ({ id: x.id, focus: x.focus, state: x.state, runtime_contract_version: x.runtimeContractVersion, research_plan_version: x.researchPlanVersion, research_plan: summarizePlan(x.researchPlan), budget: x.budget, stop_reason: x.stopReason, created_at: x.createdAt.toISOString(), finished_at: x.finishedAt?.toISOString() ?? null })); }

async function finishExhausted(db: NonNullable<ReturnType<typeof getDatabase>>, sessionId: string, taskId: string, sheetId: string, vehicleId: string, reason: string, correlationId: string, organizationId: string): Promise<{ id: string; state: string; technical_sheet_id: string; vehicle_configuration_id: string }> { await db.transaction(async (tx) => { await tx.update(researchSessionTasks).set({ state: "research_exhausted", providerCallsUsed: 1, stopReason: reason, finishedAt: new Date() }).where(eq(researchSessionTasks.id, taskId)); await tx.update(researchSessions).set({ state: "research_exhausted", stopReason: reason, finishedAt: new Date(), budget: { max_tasks: 1, max_provider_calls: 1, provider_calls: 1, mode: "simulated" } }).where(eq(researchSessions.id, sessionId)); await tx.update(fieldResearchStates).set({ state: "research_exhausted", reasonCode: reason, updatedAt: new Date() }).where(eq(fieldResearchStates.researchSessionId, sessionId)); await appendResearchSessionEvent(tx, { sessionId, organizationId, type: "task_finished", correlationId, metadata: { state: "research_exhausted", provider_calls_used: 1, stop_reason: reason } }); await appendResearchSessionEvent(tx, { sessionId, organizationId, type: "session_exhausted", correlationId, metadata: { state: "research_exhausted", stop_reason: reason } }); }); await recordResearchSessionQualityImpact(sessionId); return { id: sessionId, state: "research_exhausted", technical_sheet_id: sheetId, vehicle_configuration_id: vehicleId }; }
function toResearchPlanTask(task: typeof researchSessionTasks.$inferSelect): ResearchPlanTask { return { sequence: task.sequenceNumber, kind: "targeted_collection", targetPaths: asStrings(task.targetPaths), sourceStrategy: task.sourceStrategy === "official_only" ? "official_only" : "evidence_aware", officialDomains: asStrings(task.officialDomains), allowedSourceTypes: asStrings(task.allowedSourceTypes), providerCallBudget: task.providerCallBudget }; }
function sourcePolicyForTask(policy: Awaited<ReturnType<typeof readSourcePolicy>>, task: ResearchPlanTask): Awaited<ReturnType<typeof readSourcePolicy>> { return task.sourceStrategy === "official_only" ? { ...policy, markets: policy.markets.filter((market) => market.officialDomains.some((domain) => task.officialDomains.includes(domain))), partnerDomains: [], partnerSourceTypes: [] } : policy; }
function hasOfficialEvidence(response: unknown, policy: Awaited<ReturnType<typeof readSourcePolicy>>, task: ResearchPlanTask): boolean { const sources = Array.isArray((response as { fontes_utilizadas?: unknown }).fontes_utilizadas) ? (response as { fontes_utilizadas: Array<{ url?: unknown; tipo?: unknown }> }).fontes_utilizadas : []; return sources.some((source) => { const url = source.url; const type = source.tipo; return typeof url === "string" && typeof type === "string" && policy.officialSourceTypes.includes(type) && task.officialDomains.some((domain) => hostnameOf(url) === domain); }); }
function hasUnresolvedTarget(response: unknown, targetPaths: string[]): boolean { const sheet = (response as { ficha_tecnica?: unknown }).ficha_tecnica; return targetPaths.some((path) => { const field = path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" ? (value as Record<string, unknown>)[key] : undefined, sheet); const status = field && typeof field === "object" ? (field as Record<string, unknown>).status : undefined; return status !== "confirmado"; }); }
function summarizePlan(value: unknown): unknown { const plan = value && typeof value === "object" ? value as Partial<ResearchPlan> : undefined; return plan ? { version: plan.version, focus: plan.focus, source_strategy: plan.sourceStrategy, target_count: plan.targetCount, task_count: plan.taskCount, provider_call_budget: plan.providerCallBudget, exhaustion_reason: plan.exhaustionReason ?? null } : null; }
function asStrings(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function hostnameOf(value: string): string | undefined { try { return new URL(value).hostname; } catch { return undefined; } }
