import { and, desc, eq, gte, inArray, lt } from "drizzle-orm";
import type { AuthContext } from "./authentication";
import { getDatabase } from "./db/client";
import { auditEvents, organizationMembers, organizationUsagePolicies, usageAlertRecipients, usageAlerts, usageEvents } from "./db/schema";
import { HttpError } from "./types";

export interface UsageSummary { definition: string; period: string; starts_at: string; ends_at: string; successful_units: number; failed_attempts: number; breakdown: Array<{ action: "technical_sheet_persisted" | "technical_sheet_persist_failed"; outcome: "succeeded" | "failed"; units: number; events: number }>; }
export interface UsageAlertView { id: string; period: string; threshold_units: number; total_units: number; policy_version: number; state: "open"; created_at: string; acknowledged_at: string | null; }

export async function readUsageSummary(actor: AuthContext, period: string): Promise<UsageSummary> {
  const { start, end } = parsePeriod(period); const db = requireDb();
  const rows = await db.select({ action: usageEvents.action, outcome: usageEvents.outcome, units: usageEvents.units }).from(usageEvents).where(and(eq(usageEvents.organizationId, actor.organizationId), gte(usageEvents.createdAt, start), lt(usageEvents.createdAt, end)));
  const grouped = new Map<string, { action: "technical_sheet_persisted" | "technical_sheet_persist_failed"; outcome: "succeeded" | "failed"; units: number; events: number }>();
  for (const row of rows) { if (!isUsageAction(row.action) || !isUsageOutcome(row.outcome)) continue; const key = `${row.action}:${row.outcome}`; const entry = grouped.get(key) ?? { action: row.action, outcome: row.outcome, units: 0, events: 0 }; entry.units += row.units; entry.events += 1; grouped.set(key, entry); }
  const breakdown = [...grouped.values()].sort((a, b) => a.action.localeCompare(b.action));
  return { definition: "Cada ficha técnica persistida com sucesso vale 1 unidade. Falhas valem 0 e não representam cobrança, cota ou preço.", period, starts_at: start.toISOString(), ends_at: end.toISOString(), successful_units: breakdown.filter((item) => item.outcome === "succeeded").reduce((total, item) => total + item.units, 0), failed_attempts: breakdown.filter((item) => item.outcome === "failed").reduce((total, item) => total + item.events, 0), breakdown };
}

export async function recordUsageFailure(actor: AuthContext, requestId: string): Promise<void> { const db = requireDb(); await db.insert(usageEvents).values({ organizationId: actor.organizationId, accountId: actor.accountId, memberId: actor.memberId, action: "technical_sheet_persist_failed", outcome: "failed", units: 0, requestId }).onConflictDoNothing(); }
export async function updateUsagePolicy(actor: AuthContext, thresholdUnits: number, isActive: boolean, requestId: string): Promise<{ threshold_units: number; is_active: boolean; version: number }> { const db = requireDb(); const result = await db.transaction(async (tx) => { const [current] = await tx.select().from(organizationUsagePolicies).where(eq(organizationUsagePolicies.organizationId, actor.organizationId)).limit(1); const version = (current?.version ?? 0) + 1; const [policy] = await tx.insert(organizationUsagePolicies).values({ organizationId: actor.organizationId, thresholdUnits, isActive, version, updatedByMemberId: actor.memberId, updatedAt: new Date() }).onConflictDoUpdate({ target: organizationUsagePolicies.organizationId, set: { thresholdUnits, isActive, version, updatedByMemberId: actor.memberId, updatedAt: new Date() } }).returning(); await tx.insert(auditEvents).values({ organizationId: actor.organizationId, accountId: actor.accountId, memberId: actor.memberId, action: "usage.policy_updated", resourceType: "usage_policy", resourceId: actor.organizationId, outcome: "allowed", requestId }); return { threshold_units: policy.thresholdUnits, is_active: policy.isActive, version: policy.version }; }); if (result.is_active) await evaluateUsagePolicy(actor).catch(() => undefined); return result; }
export async function readUsageAlerts(actor: AuthContext): Promise<{ policy: { threshold_units: number; is_active: boolean; version: number } | null; alerts: UsageAlertView[] }> { const db = requireDb(); const [policy, alerts] = await Promise.all([db.select().from(organizationUsagePolicies).where(eq(organizationUsagePolicies.organizationId, actor.organizationId)).limit(1), db.select().from(usageAlerts).where(eq(usageAlerts.organizationId, actor.organizationId)).orderBy(desc(usageAlerts.createdAt)).limit(50)]); const recipients = alerts.length ? await db.select().from(usageAlertRecipients).where(and(eq(usageAlertRecipients.memberId, actor.memberId), inArray(usageAlertRecipients.usageAlertId, alerts.map((alert) => alert.id)))) : []; const acknowledged = new Map(recipients.map((recipient) => [recipient.usageAlertId, recipient.acknowledgedAt?.toISOString() ?? null])); return { policy: policy[0] ? { threshold_units: policy[0].thresholdUnits, is_active: policy[0].isActive, version: policy[0].version } : null, alerts: alerts.map((alert) => ({ id: alert.id, period: alert.period, threshold_units: alert.thresholdUnits, total_units: alert.totalUnits, policy_version: alert.policyVersion, state: "open", created_at: alert.createdAt.toISOString(), acknowledged_at: acknowledged.get(alert.id) ?? null })) }; }
export async function acknowledgeUsageAlert(actor: AuthContext, alertId: string, requestId: string): Promise<{ state: "acknowledged" }> { const db = requireDb(); return db.transaction(async (tx) => { const [alert] = await tx.select().from(usageAlerts).where(and(eq(usageAlerts.id, alertId), eq(usageAlerts.organizationId, actor.organizationId))).limit(1); if (!alert) throw new HttpError(404, "Alerta indisponivel."); await tx.insert(usageAlertRecipients).values({ usageAlertId: alert.id, memberId: actor.memberId, acknowledgedAt: new Date() }).onConflictDoUpdate({ target: [usageAlertRecipients.usageAlertId, usageAlertRecipients.memberId], set: { acknowledgedAt: new Date() } }); await tx.insert(auditEvents).values({ organizationId: actor.organizationId, accountId: actor.accountId, memberId: actor.memberId, action: "usage.alert_acknowledged", resourceType: "usage_alert", resourceId: alert.id, outcome: "allowed", requestId }); return { state: "acknowledged" as const }; }); }
export async function evaluateUsagePolicy(actor: AuthContext): Promise<void> { const db = requireDb(); await db.transaction(async (tx) => evaluateUsagePolicyInTransaction(tx, actor)); }
export async function evaluateUsagePolicyInTransaction(tx: any, actor: AuthContext): Promise<void> { const [policy] = await tx.select().from(organizationUsagePolicies).where(and(eq(organizationUsagePolicies.organizationId, actor.organizationId), eq(organizationUsagePolicies.isActive, true))).limit(1); if (!policy) return; const now = new Date(); const period = now.toISOString().slice(0, 7); const { start, end } = parsePeriod(period); const rows = await tx.select({ units: usageEvents.units, outcome: usageEvents.outcome }).from(usageEvents).where(and(eq(usageEvents.organizationId, actor.organizationId), gte(usageEvents.createdAt, start), lt(usageEvents.createdAt, end))); const total = rows.filter((row: { outcome: string }) => row.outcome === "succeeded").reduce((sum: number, row: { units: number }) => sum + row.units, 0); if (total < policy.thresholdUnits) return; const [alert] = await tx.insert(usageAlerts).values({ organizationId: actor.organizationId, period, thresholdUnits: policy.thresholdUnits, totalUnits: total, policyVersion: policy.version, state: "open" }).onConflictDoNothing().returning(); if (!alert) return; const admins = await tx.select({ id: organizationMembers.id }).from(organizationMembers).where(and(eq(organizationMembers.organizationId, actor.organizationId), eq(organizationMembers.status, "active"), eq(organizationMembers.role, "admin"))); if (admins.length) await tx.insert(usageAlertRecipients).values(admins.map((admin: { id: string }) => ({ usageAlertId: alert.id, memberId: admin.id }))).onConflictDoNothing(); await tx.insert(auditEvents).values({ organizationId: actor.organizationId, accountId: actor.accountId, memberId: actor.memberId, action: "usage.alert_created", resourceType: "usage_alert", resourceId: alert.id, outcome: "allowed", requestId: `usage-alert:${alert.id}` }); }
export function parseUsagePeriod(value: unknown): string { if (typeof value !== "string" || !/^\d{4}-(0[1-9]|1[0-2])$/.test(value)) throw new HttpError(400, "Periodo de consumo invalido."); return value; }
function parsePeriod(period: string) { if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(period)) throw new HttpError(400, "Periodo de consumo invalido."); const [year, month] = period.split("-").map(Number); const start = new Date(Date.UTC(year, month - 1, 1)); const end = new Date(Date.UTC(year, month, 1)); return { start, end }; }
function isUsageAction(value: string): value is "technical_sheet_persisted" | "technical_sheet_persist_failed" { return value === "technical_sheet_persisted" || value === "technical_sheet_persist_failed"; }
function isUsageOutcome(value: string): value is "succeeded" | "failed" { return value === "succeeded" || value === "failed"; }
function requireDb() { const db = getDatabase(); if (!db) throw new HttpError(503, "Consumo requer persistencia PostgreSQL ativa."); return db; }
